### ISSUE TITLE
Missing schematic

### ISSUE THREAD

**Issue by zebu1er** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#1]
It's very necessary to know about what GPIOs are connected with what (pullup, led, IC, ...) when using the board.
Most of the boards maker supply it, is it possible to have it too ?

**Comment by diasarmando** [comment]
I need also the schematic.

**Comment by CrazyRs6** [comment]
I also am looking for a schematic. Especially the clock lines

**Comment by kymodoke** [comment]
+1. I've got five of these boards and I really need the schematic!

**Comment by CrazyRs6** [comment]
@kymodoke @diasarmando @zebu1er 

I have been working on this module for a while now, and finally it seems to be working. I have followed the schematic from waveshare: 
https://www.waveshare.com/w/upload/0/08/LAN8720-ETH-Board-Schematic.pdf

I hope this helps!

**Comment by zebu1er** [comment]
@CrazyRs6
Thanks !
