### ISSUE TITLE
Not work ETH.linkUp()

### ISSUE THREAD

**Issue by DoctorDeatch** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#15]
Greetings. tell me for what reason the ETH.linkUp() function does not work - it always returns "0"

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/218307473-3b37e36a-4a35-4cf5-a00a-990d5193d284.png)
Because this function has been deprecated in the version of idf-4. x
