### ISSUE TITLE
WiFiEvent on board V1.1

### ISSUE THREAD

**Issue by BackenTrini** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#19]
Hi,

I've got a board version 1.1 ..

After some debugging I found out that the returned event values in "void WiFiEvent(WiFiEvent_t event)" do not correspond to to any predefined variable (eg. SYSTEM_EVENT_ETH_START).

My code gets a valid DHCP-lease.

The returned values for "event" are : 

18
20
22

Any hint where I can find information on this .. ?

I attache the used code and the debugging output.

Thanks.

[Luc_2_LILYGO.zip](https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE/files/9819727/Luc_2_LILYGO.zip)

**Comment by lewisxhe** [comment]
This is because the example was written two years ago. The wifi event macro has been replaced in the new ArduinoESP32. Please reuse the newly uploaded example
