### ISSUE TITLE
Different TF pins in example and image

### ISSUE THREAD

**Issue by EsserPrototyping** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#2]
In the code example MOSI is pin 15, but on the image it shows pin 12.
The SCLK pin is 14 in the example, but 15 on the image.
What is true?
Also the use of pin 17 should be mentioned on the image for completeness.

Thanks! Steffen

**Comment by EsserPrototyping** [comment]
Oh, and pin 5 for NRST should be mentioned on the image also.

**Comment by lewisxhe** [comment]
The picture is wrong and has been corrected
