### ISSUE TITLE
How to configure ETH.h for static IP and port ?

### ISSUE THREAD

**Issue by creepscompilation** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#20]
I want to be able to select DHCP or STATIC modes.
I have the LilyGo PoE working with DHCP Dynamic mode, no problem.

However, I am unable to configure the ETH.h library with a STATIC IP address and port number?
Here is my code..

    if (mode.indexOf("Static") > -1)    // WORKS when STATIC mode is selected,
    {    / / STATIC MODE SELECTED
      ETH.begin(ETH_ADDR, ETH_POWER_PIN, ETH_MDC_PIN, ETH_MDIO_PIN, ETH_TYPE, ETH_CLK_MODE); // needed for LilyGo Board
      local_IP.fromString(ip); // STATIC IP Address 
      if (!ETH.config(local_IP, gateway, subnet, primaryDNS, secondaryDNS)) {
      Serial.println("Static IP Failed to configure");
      } else {
        Serial.println("Static IP configured OK.."); 
        Serial.println(local_IP); // Executes and makes it HERE, but I am unable to connect to
      }            
    }
    else
    {  // DHCP DYNAMIC MODE SELECTED and WORKS ALL the WAY..
        ETH.begin(ETH_ADDR, ETH_POWER_PIN, ETH_MDC_PIN, ETH_MDIO_PIN, ETH_TYPE, ETH_CLK_MODE); //Added
        ip_dyna=ETH.localIP().toString();
        Serial.println("Dynamic IP: "+ip_dyna);
    }   
    
    port_dyna=port;
    ETHserver.begin(port_dyna.toInt()); // Port number to be used
}

**Comment by lewisxhe** [comment]
You should use ETH Config Configure the static IP used
https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE/blob/c163e5d32fa885fd41c5093eb6c784323285a764/src/src.ino#L131
