### ISSUE TITLE
Hardware Interrupt Pins on LilyGO POE?

### ISSUE THREAD

**Issue by martinmmi** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#22]
Hey, are there some GPIOs on LilyGO-T-ETH-POE which have the Hardware Interrupt Functionality? Maybe IO36, 39, 34, etc.

Thanks
-Martin

**Comment by lewisxhe** [comment]
Esp32 All GPIO can be interrupted.

**Comment by martinmmi** [comment]
Thanks!
