### ISSUE TITLE
Multiple SPI Interfaces

### ISSUE THREAD

**Issue by martinmmi** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#23]
Hello, i have a question. I am working with the T-ETH-POE Board and an SPI-LoRa-Shield and an 0,96 Monochrom SPI OLED.

For the OLED i used this lib: https://github.com/olikraus/u8g2
And for LORA i used this lib: https://github.com/sandeepmistry/arduino-LoRa

That is the constructor for the OLED:
U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ DISPLAY_CS, /* dc=*/ DISPLAY_SCLK, /* reset=*/ DISPLAY_RST);

And here iam initializing the SPI for LORA:
SPI.begin(LORA_SCLK, LORA_MISO, LORA_MOSI, LORA_CS);

When i am initializing the OLED and LORA as above in writing the code together, i get the error: SPI-Connection to LORA Modul failed.  Without  U8G2 it works fine. Everytime when i communicate with one SPI-Interface, i put the CS-Signal LOW.

How can i work with multiple spi interfaces with the LilyGO-T-ETH board?

Many thanks!

**Comment by lewisxhe** [comment]
Which pins do you use?

**Comment by martinmmi** [comment]
MOSI 15, MISO 02, SCLK 14 und for CS for each spi device on gpio.

**Comment by lewisxhe** [comment]
When sharing SPI bus with SD card, you need to disable the CS of other SPI, that is, set it to HIGH

**Comment by martinmmi** [comment]
Yeah, i did it. But i think there is somewhere a other error that i cant work with display and lora together. Maybe, i wait for the spi oled and when it connected, i will try again

**Comment by lewisxhe** [comment]
33 None of the above can be used as output, that is, as CS

**Comment by martinmmi** [comment]
Which pins i can use than for CS? Are every GPIO only inputs?

**Comment by lewisxhe** [comment]
MISO INPUT
MOSI OUTPUT
SCK OUTPUT
CS OUTPUT

**Comment by martinmmi** [comment]
Yeah, but what is in my case, when i connect a other spi device? What is with the gpios in the right upper corner? There are only input??? 

![pin](https://user-images.githubusercontent.com/118231543/218317359-be8bfad8-9f76-4e01-aee3-cb8f317578a4.png)

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/218317552-a08cd9d4-4800-45c7-be84-baed8b99dd49.png)

**Comment by martinmmi** [comment]
Thanks so much. I will try it when i have the display again. 👍

**Comment by lewisxhe** [comment]
Please reopen it if there is any problem
