### ISSUE TITLE
I2C on Downloaderboard available?

### ISSUE THREAD

**Issue by martinmmi** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#24]
Hello, is there a pindocumentation for the original LilyGO Downloaderboard available?

Thanks much
Martin

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/218302369-07e6a323-3dd7-4363-b896-8510225c27e8.png)
As can be seen from the schematic diagram, it only connects the pin for download

**Comment by martinmmi** [comment]
Okay, and the GPIOs on the Downloader Board?

**Comment by lewisxhe** [comment]
The only GPIO0 and RX TX, are you sure you want to use them?

**Comment by martinmmi** [comment]
I mean this pins. IO12, 4, 15, 2, 13, 14, 0

But yeah, i see it now. Thats only io what you need for the download board. Only 0, RX and TX are new at this board.

![pin](https://user-images.githubusercontent.com/118231543/218319628-dab3514a-1dd1-4ed0-b816-3577c3f92c6d.png)

**Comment by martinmmi** [comment]
Why the I2C pins are not available from the esp32?

**Comment by lewisxhe** [comment]
I understand what you mean. These are not available. For how to use other pins, please see here https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE/blob/master/examples/SPI_Wire_DevicesExample/SPI_Wire_DevicesExample.ino
