### ISSUE TITLE
UDP Broadcast Example

### ISSUE THREAD

**Issue by ruudboon** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#26]
I'm struggling getting UDP broadcast receiving with this decide.
Could you please add an UDP receiving example for broadcast packets?

**Comment by lewisxhe** [comment]
see there 


https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE/tree/master/examples/UDPClientReceiver

**Comment by lewisxhe** [comment]
If there is any problem, please restart it

**Comment by ruudboon** [comment]
Thank you this works greatl.
