### ISSUE TITLE
Power Issue

### ISSUE THREAD

**Issue by cheeseshark** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#31]
Greetings,

One of the boards I purchased from you stopped working after about two weeks.

The board is extremely hot to the touch and the ESD label is partially melted.

This was after running the board for about 3 days via POE.  It ran fine for about 7 days when powered by USB.

Please advise to the next steps I should take.  I have 9 other boards here that I just received today, let me know if this is an issue and I should return all 10, or if it is a one off, and you will be sending a replacment.

Thank you in advance

Mike

**Comment by lewisxhe** [comment]
Sorry, there may be some individual problems. Please contact the seller for replacement.
