### ISSUE TITLE
MQTT broker

### ISSUE THREAD

**Issue by kjastra** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#33]
Good day! Can we use Ethernet interface for MQTT publish / subscribe. May be you have any example? Thank you!

**Comment by htue** [comment]
Yes its defently possible, 

[Andreas Spiess](https://www.youtube.com/@AndreasSpiess) has a great tutorial
https://www.youtube.com/watch?v=v8JodmdxIKU&t=580s

good luck

**Comment by kjastra** [comment]
Thank you very much!

**Comment by lewisxhe** [comment]
Done.
https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE/tree/master/examples/MQTTClient
