### ISSUE TITLE
5V pin for connection of sensors

### ISSUE THREAD

**Issue by fromCologne** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#4]
Is there a 5V pin or a soldering point where I can access 5V?
A published schematic would be great.

**Comment by andyboeh** [comment]
Even with the published schematic, I'm unsure if it's possible to tap 5V somewhere in PoE mode - any ideas?

**Comment by huub66** [comment]
anyone found a way to connect 5v sensors to this board?

**Comment by kymodoke** [comment]
That is what Logic Level Converters are made for: https://learn.sparkfun.com/tutorials/bi-directional-logic-level-converter-hookup-guide

**Comment by kymodoke** [comment]
On the schematics https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE/blob/master/schematic/T-ETH-POE.pdf there are some components referred to 5V (SY8089AAAC and WPM2015), but I don't know if that comes from USB or from PoE source.

**Comment by andyboeh** [comment]
@lewisxhe What is the solution?

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/218307114-e44d8697-8fd0-48ff-b06a-3bb94c167e3b.png)
5V source is connected with VBUS and POE, but no external plug is reserved

**Comment by andyboeh** [comment]
Thanks for the clarification, that really is the solution :)

**Comment by kimble4** [comment]
And it's eminently practical to solder a header pin or wire to D5, which is large and accessible on the top side of the board.

**Comment by lewisxhe** [comment]
Indeed, this is not considered in the design of hardware. If there is a revised version later, I will make suggestions to the hardware design

**Comment by jamesgohl** [comment]
> And it's eminently practical to solder a header pin or wire to D5, which is large and accessible on the top side of the board.

My thoughts exactly.  There are 2 * 3v3 pins on the 2*8 header.

Would this be a viable modification?

![POE](https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE/assets/1788271/d2aaac06-4dc2-4f4d-8f93-cfd65027b5f4)

Whilst I am no electronic engineer, I am learning. Have I got the correct MOSFET from the schematic, where the source pin connects to the D5 line?

**Comment by hn** [comment]
This is how I grabbed 5V from the cathode of diode D5 (SS34). The cable was fixed with some epoxy glue to the ethernet connector. Please do not complain about the soldering quality, I only had a flame thrower at hand.

![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-POE/assets/11134981/c3d6cd0c-d163-4582-86ac-185064770df8)

**Comment by victorclaessen** [comment]
> This is how I grabbed 5V from the cathode of diode D5 (SS34). The cable was fixed with some epoxy glue to the ethernet connector. Please do not complain about the soldering quality, I only had a flame thrower at hand.

Thank you that was very useful!
