### ISSUE TITLE
Writing in the SD card and example problems

### ISSUE THREAD

**Issue by tratorey** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#6]
I'm working with the board and I tried to run the example using platformio. First I want to ask if there is a prefered board just to work in platformio with the LilyGO. The second question is about the example, I ran the example on my board and I'm having the next problem, It isn't printing by serial nothing at all. This is a little bit extrange and I changed some things trying to obtain something and I couldn't. Just to finish I want to know if you have some examples on how to write in the SD card. I understand that in the example you are initializing it and printing the amount of free memory by serial.

 I'm having those problems so I wait for some help if it's posible.

Thank you

**Comment by lewisxhe** [comment]
Please check the latest examples
