### ISSUE TITLE
Ethernet not working

### ISSUE THREAD

**Issue by tilchl** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#7]
When i run the exmaple sketch i get phy errors. I tried changing a few things around nohting works
I have the 1.0 Board with the WROOM no Pram

```c#
E (1200) emac: Timed out waiting for PHY register 0x2 to have value 0x0007(mask 0xffff). Current value 0xffff
E (2201) emac: Timed out waiting for PHY register 0x3 to have value 0xc0f0(mask 0xfff0). Current value 0xffff
E (2201) emac: Initialise PHY device Timeout
[E][ETH.cpp:101] begin(): esp_eth_enable error: -1
```

```c
#define ETH_CLK_MODE    ETH_CLOCK_GPIO17_OUT
#define ETH_POWER_PIN   -1
#define ETH_TYPE        ETH_PHY_LAN8720
#define ETH_ADDR        0
#define ETH_MDC_PIN     23
#define ETH_MDIO_PIN    18
#define NRST            5
```

**Comment by dok-net** [comment]
Though this issue predates the breaking change in https://github.com/espressif/arduino-esp32/pull/6259 that was fixed in https://github.com/espressif/arduino-esp32/pull/6527, it might help to revisit this issue, using current master of the arduino-esp32 code.
