### ISSUE TITLE
Can't flash the board

### ISSUE THREAD

**Issue by bangadrum** [Xinyuan-LilyGO/LilyGO-T-ETH-POE#8]
Using the proper programmer daughter board, and data LEDs flashing on that board so connection seems to be fine, but no combination of RST/IO0 is letting me flash the board. 
I've tried ESPHome Flasher and PyFlasher - is there a recommended tool for flashing these boards?

**Comment by kymodoke** [comment]
I don't use the official programmer but a simple CP2102 USB to UART bridge (as pins on the side for the programmer are just plain 3V-GND-.-.-RX-TX).
I always use the good old and reliable [esptool.py](https://github.com/espressif/esptool) to flash my ESP boards, and also for my LilyGO-T-ETH-POE boards.

Here how I do with my CP2102 programmer:
1. Remove any power source (like USB-C), and don't plug yet the USB cable of the programmer to your computer.
2. press the "BOT" button on the board and keep it pressed.
3. plug the USB cable of your programmer (it will power on the board), while still keeping the BOT button pressed.
4. release the button after 2 seconds.
-> the board will boot in programming mode.

**Comment by vanroy-b** [comment]
We've been unable to flash the device when an sd card is inserted, we remove it to flash new firmware

**Comment by OmegaModr** [comment]
Hi, can confirm that the firmware is working, mind including it in your regular builds?

I'll leave it running if it encounters any issues
